name: Blog CI/CD

# 触发条件：在 push 到 hexo-blog-backup 分支后触发
on:
  push:
    branches: 
      - master
    paths:
      - '2020/**.md'
      - '2021/**.md' 
      - 'hexo'

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Setup node
      # 设置 node.js 环境
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Cache node modules
      # 设置包缓存目录，避免每次下载
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install hexo dependencies
      # 下载 hexo-cli 脚手架及相关安装包
      run: |
        npm install hexo-cli gulp -g
        mkdir hexo-blog
        cd hexo-blog
        hexo init
        npm install hexo-deployer-git --save
        rm -rf source/_posts/*
        cp ../hexo/* . -r
        cp ../2020/  source/_posts/ -r
        cp ../2021/ source/_posts/ -r
        git clone https://github.com/theme-next/hexo-theme-next themes/next
        
    - name: Generate files and deploy
      # 编译 markdown 文件
      run: |
        git config user.name "zhangolve.automation"
        git config user.email "zhangolve@gmail.com"
        hexo clean
        hexo g
        hexo d
