name: Blog CI/CD

# 触发条件：在 push 到 hexo-blog-backup 分支后触发
on:
  push:
    branches: 
      - master
    paths:
      - '2020/**.md'
      - '2021/**.md' 

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Setup node
      # 设置 node.js 环境
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node modules
      # 设置包缓存目录，避免每次下载
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: gatsby init 
        #比较当前这个目录有没有变化
      # 下载 hexo-cli 脚手架及相关安装包
      run: |
        npm install gatsby-cli  -g
        gatsby new gatsby-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme
        npm install @mdx-js/mdx

    - name: Copy files
      run: |
        rm -rf gatsby-blog/content/posts/*
        cp 101xin/*.md gatsby-blog/content/posts/ -r
        cp 101xin/gatsby-config.js gatsby-blog

    - name: Build files
      run: |
        cd gatsby-blog
        npm run build

    - name: Deploy hexo blog
      env: 
        # Github 仓库
        GITHUB_REPO: github.com/zhangolve/my-blog
      # 将编译后的博客文件推送到指定仓库
      run: |
        rm -rf docs
        mkdir docs
        cp CNAME docs 
        cp -r gatsby-blog/public/* docs
        git init && cd docs && git add .
        git config user.name "zhangolve.automation"
        git config user.email "zhangolve@gmail.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master
