name: History today

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string， utc timezone
    - cron:  '0 23 * * *'


env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    name: get history blog
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        cache: 'pip'
        cache-dependency-path: 'today/requirements.txt'
    - run: |
        cd today
        pip install -r requirements.txt
        python today.py
